#!/usr/bin/env node

/**
 * Generate TypeScript types from modular OpenAPI specifications
 * Usage: node scripts/generate-api-types.ts
 */

import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { writeFileSync } from 'fs';
import generateSchema, { astToString } from 'openapi-typescript';
import type { OpenAPI3 } from 'openapi-typescript';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const outputFile = join(__dirname, '../api-types/generated-types.d.ts');

const bannerComment = `/**
 * ⚠️  AUTO-GENERATED FILE - DO NOT MODIFY ⚠️
 *
 * This file is automatically generated from OpenAPI specifications.
 *
 * To regenerate this file after updating OpenAPI specs:
 * 1. Update your OpenAPI specification files in open-api-specs/
 * 2. Run: cd shared && pnpm generate-types
 *
 * This ensures type safety between your API contracts and TypeScript code.
 */

`;

async function generateApiTypes() {
  try {
    console.log('🔧 Importing OpenAPI specs...');
    const specsModule = await import('../open-api-specs/index.js');
    const specExports = Object.keys(specsModule);
    console.log(`📁 Found ${specExports.length} spec exports: ${specExports.join(', ')}`);

    // Base OpenAPI specification (OpenAPI 3.1)
    const baseOpenApi: OpenAPI3 = {
      openapi: '3.1.0',
      info: {
        title: 'App Template API',
        version: '1.0.0',
        description: 'API for managing application entities'
      },
      servers: [{ url: '/api/v1', description: 'API v1', variables: {} }],
      components: {
        schemas: {
          ApiErrorResponse: {
            type: 'object',
            properties: {
              error: {
                type: 'object',
                properties: {
                  message: { type: 'string' },
                  code: { type: 'string' },
                  details: { type: 'object' }
                },
                required: ['message']
              }
            },
            required: ['error']
          }
        }
      },
      paths: {}
    };

    // Combine specs
    console.log('🔗 Combining OpenAPI specifications...');
    const { schemas, paths } = specsModule as { schemas?: Record<string, any>; paths?: Record<string, any> };
    
    if (schemas && baseOpenApi.components?.schemas) {
      Object.assign(baseOpenApi.components.schemas, schemas);
    }
    if (paths && baseOpenApi.paths) {
      Object.assign(baseOpenApi.paths, paths);
    }

    // Generate and write types
    console.log('🔧 Generating TypeScript types...');
    const typescriptTypes = await generateSchema(baseOpenApi);
    const typescriptTypesString = bannerComment + astToString(typescriptTypes);
    writeFileSync(outputFile, typescriptTypesString);

    console.log('✅ API types generated successfully!');
    console.log(`📁 Output: ${outputFile}`);
    console.log(`📊 Combined ${specExports.length} OpenAPI spec files`);

  } catch (error) {
    console.error('❌ Failed to generate API types:', (error as Error).message);
    process.exit(1);
  }
}

generateApiTypes(); 