/**
 * ⚠️  AUTO-GENERATED FILE - DO NOT MODIFY ⚠️
 *
 * This file is automatically generated from OpenAPI specifications.
 *
 * To regenerate this file after updating OpenAPI specs:
 * 1. Update your OpenAPI specification files in open-api-specs/
 * 2. Run: cd shared && pnpm generate-types
 *
 * This ensures type safety between your API contracts and TypeScript code.
 */

export interface paths {
  '/__entityPlural__': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all entities
     * @description Retrieve a list of all entities
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of entities retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['__Entity__'][];
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create a new entity
     * @description Create a new entity with the provided data
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['New__Entity__'];
        };
      };
      responses: {
        /** @description Entity created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['__Entity__'];
            };
          };
        };
        /** @description Bad request - invalid data */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/__entityPlural__/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The entity ID */
        id: string;
      };
      cookie?: never;
    };
    /**
     * Get entity by ID
     * @description Retrieve a specific entity by its ID
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The entity ID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Entity retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['__Entity__'];
            };
          };
        };
        /** @description Entity not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
      };
    };
    /**
     * Update entity
     * @description Update an existing entity with the provided data
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The entity ID */
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name?: string;
          };
        };
      };
      responses: {
        /** @description Entity updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['__Entity__'];
            };
          };
        };
        /** @description Bad request - invalid data */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
        /** @description Entity not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
      };
    };
    post?: never;
    /**
     * Delete entity
     * @description Delete an entity by its ID
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The entity ID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Entity deleted successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Entity not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/graphs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a new graph
     * @description Creates a new graph from empty or initial state.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['NewGraph'];
        };
      };
      responses: {
        /** @description Graph created successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['Graph'];
            };
          };
        };
        /** @description Bad request - invalid data */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/graphs/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The graph ID */
        id: string;
      };
      cookie?: never;
    };
    /**
     * Get current graph
     * @description Returns the current graph.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The graph ID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Graph retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['Graph'];
            };
          };
        };
        /** @description Graph not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
      };
    };
    /**
     * Update the graph
     * @description Updates the current graph with new nodes/edges or adjacency list. Validation occurs before update.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The graph ID */
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['GraphUpdateRequest'];
        };
      };
      responses: {
        /** @description Graph updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data: components['schemas']['Graph'];
            };
          };
        };
        /** @description Bad request - invalid data or would create cycle */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
        /** @description Graph not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
      };
    };
    post?: never;
    /**
     * Delete a graph
     * @description Deletes a graph by ID.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The graph ID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Graph deleted successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Graph not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApiErrorResponse: {
      error: {
        message: string;
        code?: string;
        details?: Record<string, never>;
      };
    };
    __Entity__: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: date-time */
      createdAt: string;
    };
    New__Entity__: {
      name: string;
    };
    Graph: {
      /** Format: uuid */
      id: string;
      nodes: components['schemas']['GraphNode'][];
      edges: components['schemas']['GraphEdge'][];
      /** String representation of the graph as adjacency list */
      adjacencyList: string;
      /** Whether the graph is a valid DAG */
      isValid: boolean;
      validationErrors: components['schemas']['GraphValidationError'][];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    GraphNode: {
      /** Format: uuid */
      id: string;
      /** Auto-generated label (A, B, C, etc.) */
      label: string;
      /** X coordinate on canvas */
      x: number;
      /** Y coordinate on canvas */
      y: number;
    };
    GraphEdge: {
      /** Format: uuid */
      id: string;
      /** Format: uuid - ID of the source node */
      sourceId: string;
      /** Format: uuid - ID of the target node */
      targetId: string;
    };
    GraphValidationError: {
      type: 'CYCLE_DETECTED' | 'SELF_LOOP' | 'DUPLICATE_EDGE' | 'INVALID_NODE_REFERENCE';
      message: string;
      details?: Record<string, unknown>;
    };
    NewGraph: {
      nodes?: components['schemas']['NewGraphNode'][];
      edges?: components['schemas']['NewGraphEdge'][];
      adjacencyList?: string;
    };
    NewGraphNode: {
      label: string;
      x: number;
      y: number;
    };
    NewGraphEdge: {
      /** Format: uuid */
      sourceId: string;
      /** Format: uuid */
      targetId: string;
    };
    GraphUpdateRequest: {
      nodes?: components['schemas']['GraphNode'][];
      edges?: components['schemas']['GraphEdge'][];
      adjacencyList?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
